---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGZweWVzeGN6Cg
  CLOUDINARY_KEY: NjM5NjMxODU2NDM0ODUyCg
  CLOUDINARY_SECRET: a0hjcGREZ1JiY3pIWkttSDBQX0xUT0NKUVRZCg
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljM1Z1YVd4cmRXMWhjbkl0TWprNU55SXNJbUVpT2lKamJIaHZPR3B5WVdZd1kzVmpNbXh2WVc5cmREZDNhbVZvSW4wLkl4eU1YcUtvbks3VjdSLTkwLUpXeXcK
  DB_URL: bW9uZ29kYitzcnY6Ly9zdW5pbGt1bWFycjA5Nzo8cGFzc3dvcmQ+QHN1bmlsa3VtYXItZHMua2FiZDM4ai5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9U3VuaWxrdW1hci1EUwo
  SECRET: c3VuaWxrdW1hcg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: sunilkumarr097550/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here 

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
